[project]
name = "usd-parquet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "pyopengl>=3.1.10",
    "pyside6>=6.10.1",
    "usd-core>=25.11",
]
